version: '3.8'

services:
  finance-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-app
    ports:
      - "5000:80"
    volumes:
      - ./sqllight:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always